site_name: Python Project Template
site_url: https://your-username.github.io/your-repository-name/
site_description: A template for Python projects with MkDocs documentation.

# Theme configuration
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.expand
    - navigation.tabs
    - toc.integrate
    - content.code.copy

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Installation: getting-started/installation.md
  - Usage: usage.md
  - API Reference: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md

# Plugins
plugins:
  - search
  - mkdocs-material

# Extra configuration
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true

# Paths
docs_dir: docs
site_dir: site

# Custom CSS/JS (if needed)
extra_css:
  - css/custom.css

extra_javascript:
  - js/custom.js
